sudo: required
service: 
    - docker

befor_install: 
    - docker build -t saleh/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true saleh/react-test npm test 

after_success: 
    - docker build -t saleh/multi-client ./client 
    - docker build -t saleh/multi-server ./server
    - docker build -t saleh/multi-nginx ./nginx
    - docker build -t saleh/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin

    - docker push saleh/multi-client
    - docker push saleh/multi-server
    - docker push saleh/multi-worker
    - docker push saleh/multi-nginx 
